name: Elixir CI

on:
  push:
    branches: ["**"]
    tags:
      - "v*.*.*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ELIXIR_VERSION: "1.18"
  OTP_VERSION: "26"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir/OTP
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Cache Hex/Mix home
        uses: actions/cache@v4
        with:
          path: |
            ~/.mix
            ~/.hex
          key: hexhome-${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            hexhome-${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-

      - name: Cache deps/_build
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ env.MIX_ENV }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            mix-${{ runner.os }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ env.MIX_ENV }}-

      - name: Install dependencies
        run: mix deps.get --only $MIX_ENV

      - name: Compile
        run: mix compile

      - name: Run tests
        run: mix test
